### ISSUE TITLE
Ping TSC on deps update not from GithubBot

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/security-wg#1329]
We receive dependency update such as https://github.com/nodejs/node/pull/53406 that are created by users that might be hard and risky to review. We should probably ping TSC whenever we receive changes in the deps folder not from a GithubBot

**Comment by UlisesGascon** [comment]
I strongly agree

**Comment by RafaelGSS** [comment]
Context: https://openjs-foundation.slack.com/archives/C03Q9MS3KFB/p1718290908194829?thread_ts=1718036013.366919&cid=C03Q9MS3KFB

**Comment by Uzlopak** [comment]
To create a comment in a PR in nodejs/node repository, even on a fork you need to listen on a `pull_request_target` event 

So something like the following could be enough?

```yaml
on:
  pull_request_target:
    paths:
      - 'deps/**'

jobs:
  ping-tsc:
    runs-on: ubuntu-latest
    name: Ping the TSC
    steps:
      - name: Ping the TSC
        if: >
          github.event.pull_request.user.login == 'nodejs-github-bot'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: Pinging @tsc because of a regular change in the deps folder
          comment_tag: ping-tsc
```
